### ISSUE TITLE
Bug in building DataSet

### ISSUE THREAD

**Issue by stephenwang0317** [sohyun-l/ExLPose#1]
I recently came across your repository on GitHub and was impressed by the work you and your team have done.
I've been trying to run the 'train' and 'test' codes from your repository, but I encountered some issues that I believe might be related to the DataSet construction.

For example, the variable 'image_name' in the code corresponds to a specific image file: 

> "bright/imgs_0212_hwangridan_vid000003_exp1200_bright_000052__gain_21.68_exposure_417.png."

and it exists in the datasel ExLPose.

 However, the generated 'img_path' appears to be :
>  "/my_path/ExLPose/bright/imgs_0212hwangridan_vid000003_exp1200_img_000052__exposure_417.png," 

and 'img_path_LL' is
>  "/my_path/ExLPose/dark/imgs_0212hwangridan_vid000003_exp1200_img_000052__exposure_417.png."

 It seems that these paths do not correspond to existing images in the dataset. For example, there should be an **underscore symbol (_)** in "0212hwangridan."

I wanted to reach out and inquire whether there might be an issue with the code or if I have misunderstood something in the process. I would greatly appreciate your insights on this matter. Thank you in advance for your time and assistance.

Looking forward to your response.

**Comment by zouxuelian** [comment]
I also encountered the same problem, have you solved it?

**Comment by stephenwang0317** [comment]
> I also encountered the same problem, have you solved it?

There is a file which denotes the mapping between the bright images and dark images in the **_annotation_** folder of the dataset. I delete the code associated with the file path in the code of building dataset and simply using the mapping file to get the filename of dark images. The code works after modification.

**Comment by zouxuelian** [comment]
thank you very much

**Comment by zouxuelian** [comment]
> > I also encountered the same problem, have you solved it?
> 
> There is a file which denotes the mapping between the bright images and dark images in the **_annotation_** folder of the dataset. I delete the code associated with the file path in the code of building dataset and simply using the mapping file to get the filename of dark images. The code works after modification.

Hello, after I modified the code as you said, anno[index] keyword error occurred. So can you share the code you modified? I would be grateful.

**Comment by stephenwang0317** [comment]
> > > I also encountered the same problem, have you solved it?
> > 
> > 
> > There is a file which denotes the mapping between the bright images and dark images in the **_annotation_** folder of the dataset. I delete the code associated with the file path in the code of building dataset and simply using the mapping file to get the filename of dark images. The code works after modification.
> 
> Hello, after I modified the code as you said, anno[index] keyword error occurred. So can you share the code you modified? I would be grateful.

Here is the modified ***loader_train_pair.py*** .

https://paste.ubuntu.com/p/Qmk9x7XxFW/

***loader_eval_LL.py*** and _**loader_eval_WL.py**_ need to modify in the same way.

**Comment by zouxuelian** [comment]
> > > > I also encountered the same problem, have you solved it?
> > > 
> > > 
> > > There is a file which denotes the mapping between the bright images and dark images in the **_annotation_** folder of the dataset. I delete the code associated with the file path in the code of building dataset and simply using the mapping file to get the filename of dark images. The code works after modification.
> > 
> > 
> > Hello, after I modified the code as you said, anno[index] keyword error occurred. So can you share the code you modified? I would be grateful.
> 
> Here is the modified _**loader_train_pair.py**_ .
> 
> https://paste.ubuntu.com/p/Qmk9x7XxFW/
> 
> _**loader_eval_LL.py**_ and _**loader_eval_WL.py**_ need to modify in the same way.

Thank you very much, I will try to run it now

**Comment by liza-li** [comment]
Hi, did you encounter a prompt to log in to the wandb account initially? I followed the instructions and logged in, but then the system is indicating that I don't have permission for this project. This is quite puzzling for me.
`wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)`

**Comment by zouxuelian** [comment]
> Hi, did you encounter a prompt to log in to the wandb account initially? I followed the instructions and logged in, but then the system is indicating that I don't have permission for this project. This is quite puzzling for me. `wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)`

It seems that you need to register an account scientifically online, and then you can connect normally.

**Comment by liza-li** [comment]
> > Hi, did you encounter a prompt to log in to the wandb account initially? I followed the instructions and logged in, but then the system is indicating that I don't have permission for this project. This is quite puzzling for me. `wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)`
> 
> It seems that you need to register an account scientifically online, and then you can connect normally.

I have created an account, but after logging in, it seems that my account does not have access to this project. Have you also encountered the operation requirement to log in to your account？

**Comment by zouxuelian** [comment]
我没遇到过这个问题

**Comment by zouxuelian** [comment]
你尝试一下用github登录那，我查看我的是github登录

**Comment by liza-li** [comment]
好的谢谢谢谢

**Comment by zouxuelian** [comment]
> wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)

在train.py代码那里，有一个wandb.init（）函数，这里有三个参数，去掉最后一个参数，你试一下

**Comment by Nancy-sn** [comment]
![image](https://github.com/sohyun-l/ExLPose/assets/56101252/0e76135b-583e-4e81-a736-19604010e83e)
Hello, I would be happy to help you. Could you please provide the specific error message you are encountering along with the details of the module that is reported as missing? This will enable me to assist you in resolving the issue effectively.

**Comment by zouxuelian** [comment]
> > > > I also encountered the same problem, have you solved it?
> > > 
> > > 
> > > There is a file which denotes the mapping between the bright images and dark images in the **_annotation_** folder of the dataset. I delete the code associated with the file path in the code of building dataset and simply using the mapping file to get the filename of dark images. The code works after modification.
> > 
> > 
> > Hello, after I modified the code as you said, anno[index] keyword error occurred. So can you share the code you modified? I would be grateful.
> 
> Here is the modified _**loader_train_pair.py**_ .
> 
> https://paste.ubuntu.com/p/Qmk9x7XxFW/
> 
> _**loader_eval_LL.py**_ and _**loader_eval_WL.py**_ need to modify in the same way.

Hello, thank you very much for sharing your code. I have run the modified code. During the operation, I encountered some problems
First. I will test the model you gave me again to see the well-lit splits test ap is 0.04. When checking, I found that there is no ExLPose_test_WL-trans.json under the pytorch-cpn/256.192.model/Annotations/ExLPose/ file. Because when I compared other files, I found that the gtbbox of the .json files of low-light-easy, Low-light-normal, low-light-hard, and low-light-all should have been changed. I would like to ask about this. I would like to ask if you can provide the modified ExLPose_test_WL-trans.json or generate the code.
Second. I configured the environment according to the expose.yaml you gave me. When training the code, I found that the GPU utilization was very low, but the occupancy rate was very high, so I would like to ask you whether this problem has occurred during operation.

**Comment by guzejungithub** [comment]
> > > > I also encountered the same problem, have you solved it?
> > > 
> > > 
> > > There is a file which denotes the mapping between the bright images and dark images in the **_annotation_** folder of the dataset. I delete the code associated with the file path in the code of building dataset and simply using the mapping file to get the filename of dark images. The code works after modification.
> > 
> > 
> > Hello, after I modified the code as you said, anno[index] keyword error occurred. So can you share the code you modified? I would be grateful.
> 
> Here is the modified _**loader_train_pair.py**_ .
> 
> https://paste.ubuntu.com/p/Qmk9x7XxFW/
> 
> _**loader_eval_LL.py**_ and _**loader_eval_WL.py**_ need to modify in the same way.

楼主您好，感谢您为论文复现所做的贡献，这对我们帮助很大？我有两个问题需要请教您？
1.代码训练配置文件中    train_config.py   中  gt_path = os.path.join(root_dir, 'Annotations/ExLPose','ExLPose_train_trans.json')
这里  ExLPose_train_trans.json   文件找不到 ，请问您是怎么处理的？
2. 代码复现能否达到了论文的数据？
非常感谢您！

**Comment by guzejungithub** [comment]
> > > > > I also encountered the same problem, have you solved it?
> > > > 
> > > > 
> > > > There is a file which denotes the mapping between the bright images and dark images in the **_annotation_** folder of the dataset. I delete the code associated with the file path in the code of building dataset and simply using the mapping file to get the filename of dark images. The code works after modification.
> > > 
> > > 
> > > Hello, after I modified the code as you said, anno[index] keyword error occurred. So can you share the code you modified? I would be grateful.
> > 
> > 
> > Here is the modified _**loader_train_pair.py**_ .
> > https://paste.ubuntu.com/p/Qmk9x7XxFW/
> > _**loader_eval_LL.py**_ and _**loader_eval_WL.py**_ need to modify in the same way.
> 
> Thank you very much, I will try to run it now

您好，请问您 anno[index] keyword error 解决了没？怎么解决的？非常感谢

**Comment by stephenwang0317** [comment]
> > > > > I also encountered the same problem, have you solved it?
> > > > 
> > > > 
> > > > There is a file which denotes the mapping between the bright images and dark images in the **_annotation_** folder of the dataset. I delete the code associated with the file path in the code of building dataset and simply using the mapping file to get the filename of dark images. The code works after modification.
> > > 
> > > 
> > > Hello, after I modified the code as you said, anno[index] keyword error occurred. So can you share the code you modified? I would be grateful.
> > 
> > 
> > Here is the modified _**loader_train_pair.py**_ .
> > https://paste.ubuntu.com/p/Qmk9x7XxFW/
> > _**loader_eval_LL.py**_ and _**loader_eval_WL.py**_ need to modify in the same way.
> 
> 楼主您好，感谢您为论文复现所做的贡献，这对我们帮助很大？我有两个问题需要请教您？ 1.代码训练配置文件中 train_config.py 中 gt_path = os.path.join(root_dir, 'Annotations/ExLPose','ExLPose_train_trans.json') 这里 ExLPose_train_trans.json 文件找不到 ，请问您是怎么处理的？ 2. 代码复现能否达到了论文的数据？ 非常感谢您！

1. The file that you cannot find is in the repository. [ExLPose_train_trans.json](https://github.com/sohyun-l/ExLPose/blob/main/pytorch-cpn/256.192.model/Annotations/ExLPose/ExLPose_train_trans.json)
2. Using the pretrained model given in the readme.md, the result is the same as in the paper.

**Comment by guzejungithub** [comment]
> > > > > > I also encountered the same problem, have you solved it?
> > > > > 
> > > > > 
> > > > > There is a file which denotes the mapping between the bright images and dark images in the **_annotation_** folder of the dataset. I delete the code associated with the file path in the code of building dataset and simply using the mapping file to get the filename of dark images. The code works after modification.
> > > > 
> > > > 
> > > > Hello, after I modified the code as you said, anno[index] keyword error occurred. So can you share the code you modified? I would be grateful.
> > > 
> > > 
> > > Here is the modified _**loader_train_pair.py**_ .
> > > https://paste.ubuntu.com/p/Qmk9x7XxFW/
> > > _**loader_eval_LL.py**_ and _**loader_eval_WL.py**_ need to modify in the same way.
> > 
> > 
> > 楼主您好，感谢您为论文复现所做的贡献，这对我们帮助很大？我有两个问题需要请教您？ 1.代码训练配置文件中 train_config.py 中 gt_path = os.path.join(root_dir, 'Annotations/ExLPose','ExLPose_train_trans.json') 这里 ExLPose_train_trans.json 文件找不到 ，请问您是怎么处理的？ 2. 代码复现能否达到了论文的数据？ 非常感谢您！
> 
> 1. The file that you cannot find is in the repository. [ExLPose_train_trans.json](https://github.com/sohyun-l/ExLPose/blob/main/pytorch-cpn/256.192.model/Annotations/ExLPose/ExLPose_train_trans.json)
> 2. Using the pretrained model given in the readme.md, the result is the same as in the paper.
非常感谢您的回答  帮我解决了很久没有解决的问题   请问您的测试代码能用吗  ？我测试的时候不知哪里错了

**Comment by guzejungithub** [comment]
> > > > > > I also encountered the same problem, have you solved it?
> > > > > 
> > > > > 
> > > > > There is a file which denotes the mapping between the bright images and dark images in the **_annotation_** folder of the dataset. I delete the code associated with the file path in the code of building dataset and simply using the mapping file to get the filename of dark images. The code works after modification.
> > > > 
> > > > 
> > > > Hello, after I modified the code as you said, anno[index] keyword error occurred. So can you share the code you modified? I would be grateful.
> > > 
> > > 
> > > Here is the modified _**loader_train_pair.py**_ .
> > > https://paste.ubuntu.com/p/Qmk9x7XxFW/
> > > _**loader_eval_LL.py**_ and _**loader_eval_WL.py**_ need to modify in the same way.
> > 
> > 
> > 楼主您好，感谢您为论文复现所做的贡献，这对我们帮助很大？我有两个问题需要请教您？ 1.代码训练配置文件中 train_config.py 中 gt_path = os.path.join(root_dir, 'Annotations/ExLPose','ExLPose_train_trans.json') 这里 ExLPose_train_trans.json 文件找不到 ，请问您是怎么处理的？ 2. 代码复现能否达到了论文的数据？ 非常感谢您！
> 
> 1. The file that you cannot find is in the repository. [ExLPose_train_trans.json](https://github.com/sohyun-l/ExLPose/blob/main/pytorch-cpn/256.192.model/Annotations/ExLPose/ExLPose_train_trans.json)
> 2. Using the pretrained model given in the readme.md, the result is the same as in the paper.

**Comment by guzejungithub** [comment]
> > > > > > I also encountered the same problem, have you solved it?
> > > > > 
> > > > > 
> > > > > There is a file which denotes the mapping between the bright images and dark images in the **_annotation_** folder of the dataset. I delete the code associated with the file path in the code of building dataset and simply using the mapping file to get the filename of dark images. The code works after modification.
> > > > 
> > > > 
> > > > Hello, after I modified the code as you said, anno[index] keyword error occurred. So can you share the code you modified? I would be grateful.
> > > 
> > > 
> > > Here is the modified _**loader_train_pair.py**_ .
> > > https://paste.ubuntu.com/p/Qmk9x7XxFW/
> > > _**loader_eval_LL.py**_ and _**loader_eval_WL.py**_ need to modify in the same way.
> > 
> > 
> > 楼主您好，感谢您为论文复现所做的贡献，这对我们帮助很大？我有两个问题需要请教您？ 1.代码训练配置文件中 train_config.py 中 gt_path = os.path.join(root_dir, 'Annotations/ExLPose','ExLPose_train_trans.json') 这里 ExLPose_train_trans.json 文件找不到 ，请问您是怎么处理的？ 2. 代码复现能否达到了论文的数据？ 非常感谢您！
> 
> 1. The file that you cannot find is in the repository. [ExLPose_train_trans.json](https://github.com/sohyun-l/ExLPose/blob/main/pytorch-cpn/256.192.model/Annotations/ExLPose/ExLPose_train_trans.json)
> 2. Using the pretrained model given in the readme.md, the result is the same as in the paper.

Hello, may I ask if you are available to further discuss this issue with me? my email is zejungu@foxmail.com   if  ok, please contact me.
