### ISSUE TITLE
Question about the result of test.py

### ISSUE THREAD

**Issue by jxjx12138** [sohyun-l/ExLPose#3]
After I ran the script 'test.py' with 'Final_model.pth.rar', the evaluation results differ significantly from those in the paper. Maybe I didn't notice some default settings. 
I wanted to reach out and inquire whether there might be an issue with the code or if I have misunderstood something in the process. I would greatly appreciate your insights on this matter. Thank you in advance for your time and assistance.

Looking forward to your response.

**Comment by aoikaneko** [comment]
@jxjx12138 Hi, I am experiencing the same issue. The test results (AP) for low light conditions differ significantly from those in the paper. Have you solved this problem?
